"""empty message

Revision ID: 258fbdf803e5
Revises: d83dfedf381a
Create Date: 2020-05-19 10:15:03.594129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258fbdf803e5'
down_revision = 'd83dfedf381a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
